[project]
name = "backend"
version = "0.1.0"
description = "Cortex backend"
readme = "README.md"
authors = [
    { name = "Lakshya Tiwari", email = "imlakshya.tiwari@gmail.com" }
]
requires-python = ">=3.12"
dependencies = [
    "fastapi[standard]>=0.141.1",
]

[project.scripts]
backend = "app.main:app"

[build-system]
requires = ["uv_build>=0.12.13,<0.13.0"]
build-backend = "uv_build"

[tool.uv.build-backend]
module-name = "app"
module-root = "src"
